#! /usr/bin/env python
#
#  This file is part of usernotify.
#
#  usernotify is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  usernotify is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with usernotify.  If not, see <http://www.gnu.org/licenses/>.
#
"""Notifies users with messages."""

from argparse import ArgumentParser
from sys import exit, stderr    # pylint: disable=W0622

from usernotify import MIN_UID
from usernotify import MAX_UID
from usernotify import broadcast
from usernotify import add_notify_send_args
from usernotify import notify_send_args


def main():
    """Runs nofiy-users."""

    parser = ArgumentParser(description='Notifies users with messages.')
    add_notify_send_args(parser)
    parser.add_argument('--min-uid', type=int, metavar='UID')
    parser.add_argument('--max-uid', type=int, metavar='UID')
    args = parser.parse_args()
    min_uid = args.min_uid or MIN_UID
    max_uid = args.max_uid or MAX_UID
    uids = range(min_uid, max_uid + 1)

    try:
        return broadcast(notify_send_args(args), uids=uids)
    except PermissionError:
        print('You must be root to notify other users.', file=stderr)
        exit(2)


if __name__ == '__main__':
    main()
