#! /usr/bin/env python3
"""notify-user  Copyright (C) 2018  Richatd Neumann

    Notifies users with messages.

Usage:
    notify-users <summary> [<body>] [options]

Options:
    --urgency=LEVEL, -u             Specifies the urgency level:
                                    (low, normal, critical).
    --expire-time=TIME, -t          Specifies the timeout in milliseconds at
                                    which to expire the notification.
    --app-name=APP_NAME, -a         Specifies the app name for the icon.
    --icon=ICON[,ICON...], -i       Specifies an icon filename or stock icon to
                                    display.
    --category=TYPE[,TYPE...], -c   Specifies the notification category.
    --hint=TYPE:NAME:VALUE, -h      Specifies basic extra data to pass:
                                    (int, double, string, byte)
    --min-uid=<min_uid>             Specifies the minimum UID [default: {}].
    --max-uid=<max_uid>             Specifies the maximum UID [default: {}].
    --version, -v                   Version of the package.
"""
from sys import exit as exit_, stderr

from docopt import docopt

from usernotify import Args, MIN_UID, MAX_UID, send_all


def main(options):
    """Runs nofiy-users."""

    try:
        min_uid = int(options['--min-uid'])
    except ValueError:
        print('Invalid minimum UID.', file=stderr)
        return 1

    try:
        max_uid = int(options['--max-uid'])
    except ValueError:
        print('Invalid maximum UID.', file=stderr)
        return 1

    args = Args.from_options(options)
    uids = range(min_uid, max_uid + 1)

    try:
        return send_all(args, uids=uids)
    except PermissionError:
        print('You must be root to notify other users.', file=stderr)
        return 2


if __name__ == '__main__':
    exit_(main(docopt(__doc__.format(MIN_UID, MAX_UID))))

