#! /usr/bin/env python3
#
#  This file is part of usernotify.
#
#  usernotify is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  usernotify is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with usernotify.  If not, see <http://www.gnu.org/licenses/>.
#
"""notify-user  Copyright (C) 2018  Richard Neumann



Usage:
    notify-user <user> <summary> [<body>] [options]

Options:
    --urgency=LEVEL, -u             Specifies the urgency level:
                                    (low, normal, critical).
    --expire-time=TIME, -t          Specifies the timeout in milliseconds at
                                    which to expire the notification.
    --app-name=APP_NAME, -a         Specifies the app name for the icon.
    --icon=ICON[,ICON...], -i       Specifies an icon filename or stock icon to
                                    display.
    --category=TYPE[,TYPE...], -c   Specifies the notification category.
    --hint=TYPE:NAME:VALUE, -h      Specifies basic extra data to pass:
                                    (int, double, string, byte)
    --version, -v                   Version of the package.
"""
from argparse import ArgumentParser
from sys import exit, stderr    # pylint: disable=W0622

from usernotify import send, add_notify_send_args, notify_send_args


def main():
    """Runs nofiy-users."""

    parser = ArgumentParser(
        description='Notifies a single user with a message.')
    parser.add_argument('user', metavar='USER')
    add_notify_send_args(parser)
    args = parser.parse_args()

    try:
        return send(args.user, notify_send_args(args))
    except PermissionError:
        print('You must be root to notify other users.', file=stderr)
        exit(2)


if __name__ == '__main__':
    main()
